- .drone.yml
- tools/clean-build-all.sh
WIP. Let's see what we can do with this thing ...
> Add initial drone pipeline

- .drone.yml
- tools/build-package.sh
- tools/clean-build-all.sh
- tools/syncdeps-all.sh
Not very elegant, but it works ;)
> feat: allow to pass PACKAGE env var to pipeline to build a single package

- packages/midiomatic/PKGBUILD
Also fix `build` function to use no parallel make.
> fix: pkgdesc VST -> VST2 and no parallel build

- .drone.yml
- web/content/_footer.md
- web/layouts/index.html
- web/layouts/partials/package-details.html
- current year in footer
- no more muted colors for dirs/makedepends/checkdepends
- Close button for package details
- enable Website pipeline for PRs (only publishes on merge)
> Some website improvements

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/vcf-lv2/PKGBUILD
https://github.com/linuxmao-org/vcf-lv2
> Package vcf-lv2

- tools/README.md
- tools/prepare-build.sh
For some reason since recently this enables all packages...
> disable git diff check for modified packages

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/rakarrack-plus/.gitignore
- packages/rakarrack-plus/PKGBUILD
> Package rakarrack-plus

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/rtcqs/.gitignore
- packages/rtcqs/PKGBUILD
https://codeberg.org/rtcqs/rtcqs
I may create another package for the `python-pysimplegui` optdepend, however that's not really proaudio-related ;)
> package rtcqs

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/python-pysimplegui/PKGBUILD
This is an optional dependency for rtcqs, see #62
> package PySimpleGUI

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/paulxstretch/PKGBUILD
- packages/paulxstretch/fix-gcc12.patch
[paulxstretch](https://sonosaurus.com/paulxstretch/)
Closes #60 
**TODO**
> package paulxstretch

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/faustlive/PKGBUILD
[FaustLive](https://github.com/grame-cncm/faustlive)
**TBD**
> package faustlive

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/clap/PKGBUILD
[CLAP API headers](https://github.com/free-audio/clap)
> package clap

- packages/ola/.gitignore
- packages/ola/PKGBUILD
Removing the workaround and applying a proper patch instead.
> patch ola to fix crash and tests

- nvchecker/README.md
- nvchecker/nvchecker-notify-matrixchat.json.tmpl
- nvchecker/nvchecker-notify-matrixchat.py
- nvchecker/run-nvchecker.cron
See updated `nvchecker/README.md` for more information.
> feat: add new script for nvchecker notification to Matrix chat

- nvchecker/old_ver.json
- packages/faustlive/PKGBUILD
> update faustlive to 2.5.11

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/elephantdsp-roomreverb/PKGBUILD
- packages/elephantdsp-roomreverb/roomreverb-devendor_juce.patch
> feat: add package elephantdsp-roomreverb

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/gnome-shell-extension-gsjackctl/PKGBUILD
[gsjackctl](https://github.com/cbix/gsjackctl)
> package gsjackctl

- nvchecker/old_ver.json
- packages/jamulus/PKGBUILD
currently using the prerelease, change to 3.9.0 when the release is out!
> update jamulus to 3.9.0

- aur/packages
let's maintain this in only one place
already added osamc as co-maintainer
> add surge-xt to aur packages

- packages/surge-xt/.gitignore
- packages/surge-xt/PKGBUILD
> surge-xt: fix crash

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/fluida.lv2/PKGBUILD
- Added `aarch64` arch
- Added `check` function
- Added `lv2lint` to `checkdepends`
- Added `optdepends` on `lv2-host`
- Fixed source URL
> feat: import package 'fluida.lv2' from AUR

- nvchecker/old_ver.json
- packages/clap/PKGBUILD
Finally with proper cmake and pkg-config files 🥳
> update clap to v1.1.3

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/audiowmark/PKGBUILD
> Package audiowmark

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/clap-validator/PKGBUILD
[clap-validator](https://github.com/free-audio/clap-validator)
In the future we can use this to `check()` CLAP plugins
> package clap-validator

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/liblc3/.gitignore
- packages/liblc3/PKGBUILD
[liblc3](https://github.com/google/liblc3)
> package liblc3

- packages/python-soundfile/PKGBUILD
… with latest libsndfile with MP3 support
> fix: bump pkgrel of python-soundfile to trigger rebuild

- packages/qjackcapture/PKGBUILD
> [qjackcapture] bump pkgrel to trigger rebuild for Python 11

- nvchecker/old_ver.json
- packages/uhhyou-plugins/PKGBUILD
> uhhyou-plugins: update to v0.56.0, fix for vst3sdk 3.7.8

- packages/uhhyou-plugins/PKGBUILD
> fix: adapt for changing moduleinfo.json path between vst3sdk versions

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/python-miditk-smf/PKGBUILD
Had this lying around for a while. No reason, not to add it, imho.
> feat: add package 'python-miditk-smf'

- .drone.yml
- tools/push-aur.sh
Also:
* Don't suppress pacman output.
* Install pipeline step deps in step's command list, not hidden in script.
> [ci] fix: update package database when upgrading packages

- .drone.yml
- tools/build-package.sh
- tools/compare-checksums.sh
- tools/diff-packages.sh
- tools/prepare-build.sh
* Fix package updating in prepare build step
> [ci] feat: allow ignoring reproducible build failures

- nvchecker/old_ver.json
- packages/uhhyou-plugins/PKGBUILD
* add docs sub-module repo
* update dependencies according to namcap analysis
> feat: update package 'uhhyou-plugins' to 0.59.0-1

- packages/ola/.gitignore
- packages/ola/PKGBUILD
- Closes #251 
- blocked by #330
- (actually) blocked by OpenLightingProject/ola#1879
> ola: use legacy protobuf to fix build

- packages/paulxstretch/.gitignore
- packages/paulxstretch/PKGBUILD
> paulxstretch: fix vst3 scan

- packages/protobuf-21/PKGBUILD
- as per request [on AUR](https://aur.archlinux.org/packages/protobuf-21#comment-949240)
> protobuf-21: remove provides=protobuf

- nvchecker/old_ver.json
- packages/uhhyou-plugins/PKGBUILD
> feat: update package 'uhhyou-plugins' to 0.61.0-1

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/linux-show-player/PKGBUILD
* Fix nvchecker config entry.
* Update dependencies.
* Update make dependencies due to change from setuptools to poetry.
* Install metainfo file.
> feat: update package 'linux-show-player' to 0.6-1

- README.md
> fix: use proper pacman update commands in readme examples

- packages/jamulus/PKGBUILD
- see jamulussoftware/jamulus#3228
> jamulus: bump pkgrel to use latest qt

- nvchecker/old_ver.json
- packages/audiowmark/PKGBUILD
> feat: update package 'audiowmark' to 0.6.2-1

- aur/packages
- packages/airwindows-lv2/PKGBUILD
> feat: add 'airwindows.lv2' package to AUR

- aur/packages
- packages/airwindows-lv2/PKGBUILD
> feat: add 'airwindows-lv2' package to AUR (2nd try)

- packages/seq66/.gitignore
- packages/seq66/PKGBUILD
> seq66: liblo 0.32 compatibility

- packages/ola/.gitignore
- packages/ola/PKGBUILD
- Closes #395 
- Using OpenLightingProject/ola#1954
> ola: liblo compatibility

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/midi2-workbench/PKGBUILD
- packages/midi2-workbench/midi2-workbench.desktop
- packages/midi2-workbench/midi2-workbench.sh
- [MIDI 2.0 Workbench](https://github.com/midi2-dev/MIDI2.0Workbench)
- [Electron package guidelines](https://wiki.archlinux.org/title/Electron_package_guidelines)
- TODO
> Package midi2-workbench

- nvchecker/old_ver.json
- packages/convertwithmoss/PKGBUILD
Updated license field to have SPDX license identifier
> feat: update package 'convertwithmoss' to 8.0.0-1

- packages/vcvrack/.install
- packages/vcvrack/PKGBUILD
- packages/vcvrack/wmclass.patch
> vcvrack: set explicit WM class

- nvchecker/old_ver.json
- packages/ykchorus/PKGBUILD
* Use SPDX identifier for license field
* Add CLAP and VST3 format
> feat: update package 'ykchorus' to 0.2.4-1

- packages/ykchorus/PKGBUILD
* Update package description
* Add missing dependencies
* Don't compile in fallback audio drivers
> fix: more 'ykchorus' package fixes

- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/ot-simian1/PKGBUILD
- packages/ot-simian1/dub.json
- packages/ot-simian1/generate-manifest-ttl.py
> feat: add package 'ot-simian1' (legacy version 1)

- packages/ola/PKGBUILD
- packages/ola/fix-build-with-gcc-14.patch
* Also update license identifiers
Fixes: #448
> fix: add patch to fix building ola with GCC 14

- nvchecker/old_ver.json
- packages/raysession/PKGBUILD
fix: use SPDX license identifier
> feat: update package raysession to 0.14.4-1

- nvchecker/old_ver.json
- packages/convertwithmoss/PKGBUILD
Also install readmes and changelog as package docs
> feat: update package convertwithmoss to 11.7.0-1

- aur/packages
- nvchecker/archlinux-proaudio.toml
- nvchecker/old_ver.json
- packages/jack_link/PKGBUILD
> feat: add new package 'jack_link'

- packages/guitarix.vst/PKGBUILD
> guitarix.vst: fix dependencies

- packages/vcvrack/PKGBUILD
- packages/vcvrack/arm64-objcopy.patch
> vcvrack: fix objcopy for aarch64

- aur/packages
- packages/vcvrack-4ms/.gitignore
- packages/vcvrack-4ms/.nvchecker.toml
- packages/vcvrack-4ms/PKGBUILD
- packages/vcvrack-4ms/sdk-fixes.patch
- packages/vcvrack-4ms/sdk-path.patch
- packages/vcvrack-ahornberg/PKGBUILD
- packages/vcvrack-alefsbits/PKGBUILD
- packages/vcvrack-alikins/PKGBUILD
- packages/vcvrack-alliewayaudio-freebies/PKGBUILD
- packages/vcvrack-amalgamated-harmonics/PKGBUILD
- packages/vcvrack-not-things/.gitignore
- packages/vcvrack-not-things/.nvchecker.toml
- packages/vcvrack-not-things/PKGBUILD
- https://github.com/not-things-modular/not-things-vcv
- https://github.com/4ms/4ms-vcv
> Package VCV Rack plugins

- packages/ola/PKGBUILD
- closes #577 
- depends on #578
> ola: fix python-protobuf dependency

- packages/python-qdigitalmeter/.nvchecker.toml
- packages/python-qdigitalmeter/PKGBUILD
> Add new package 'python-qdigitalmeter'

- .drone.yml
- .gitignore
- nvchecker/README.md
- nvchecker/nvpr.sh
- packages/jamulus/PKGBUILD
The goal is to have a CI pipeline automatically open PRs for new versions, which are then manually reviewed and merged. This should save us some manual effort and time.
> Open nvchecker PRs from cron

- aur/packages
- packages/octasine/PKGBUILD
Also move libxcursor to run-time depends
> [octasine] sync to AUR
