.editorconfig
README.md
packages/mamba/PKGBUILD
tools/fmt.sh

This adds an `.editorconfig` to ensure consistent indentation (2 spaces) and (basic) formatting of PKGBUILDs. Also a script to format all PKGBUILDs using [`shfmt`](https://archlinux.org/packages/community/x86_64/shfmt/)
To check if your editor can recognize this file, see https://editorconfig.org/
Maybe someone knows a more powerful tool for linting/formatting PKGBUILDs with configurable best practices.

PKGBUILD formatting config

---

.gitignore
README.md
tools/README.md
tools/update-db.sh

[**Preview**](https://github.com/osam-cologne/archlinux-proaudio/blob/feat/badges/README.md#archlinux-proaudio)
These are generated when updating the database.
This also fixes a wrong code-fence in the tools README and improves documentation.

generate status badges

---

.drone.yml
nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json

Today there were a few incidents where apparently the CI host could not reach the docker registry and fail the pipeline run. This should not happen as all used images are generally available locally already. For regular cache maintenance I'll eventually setup another solution outside of this repo :)

improve nvchecker patterns and CI

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/midimonster/PKGBUILD

[**MIDIMonster**](https://github.com/cbdevnet/midimonster)
Regarding the depends/optdepends:
(see [building instructions](https://github.com/cbdevnet/midimonster#building-from-source))
midimonster comes with a selection of backends, some of which link to shared libs like alsa or jack. If a backend can't run because of a missing dependency, it will simply be ignored and print a fail info:
```
MIDIMonster v0.6-dist
Failed to load plugin /usr/lib/midimonster/jack.so: libjack.so.0: cannot open shared object file: No such file or directory
Registered backend openpixelcontrol
Failed to load plugin /usr/lib/midimonster/evdev.so: libevdev.so.2: cannot open shared object file: No such file or directory
Registered backend rtpmidi
Registered backend mqtt
...
```
The working backends are usable, …

Package MIDIMonster

---

.drone.yml
.gitignore
README.md
config.yml
tools/README.md
web/content/_footer.md
web/layouts/index.html
web/layouts/partials/filesize.html
web/layouts/partials/get-packages.html
web/layouts/partials/package-details.html

This builds a simple static site using [Hugo](https://gohugo.io) to be pushed to https://arch.osamc.de/.
A preview can be tested under https://arch.osamc.de/hugo-test/, or run `hugo server` from the root dir. To render the package list it expects the [files databases](https://arch.osamc.de/proaudio/aarch64/proaudio.files.tar.gz) to be extracted to `.tmp/db/{x86_64,aarch64}`.
Closes #27 
- yes, most file browsers use SI units

Simple website

---

packages/string-machine/PKGBUILD

* Add 'kxstudio-lv2-extensions' to checkdepends to get better lv2lint output.
* Ignore a few lv2lint warnings.
* Also replace occurrence of hard-coded literal package name with variable.

fix: checkdepends line was accidentally commented out

---

.drone.yml
tools/build-env.sh
tools/prepare-build.sh

Closes #10 
When running the CI pipeline locally, there is now a `.tmp/cache` directory that persists subsequent runs and caches
- pacman packages
- pacman db
- downloaded sources
This should improve build time when the drone pipeline is used locally.

Local drone cache for pacman and sources

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/kpp/PKGBUILD

[**Kapitonov Plugins Pack**](https://github.com/olegkapitonov/Kapitonov-Plugins-Pack) (LADSPA & LV2)
- maybe the `ssr` situation is a good example why more explicit = more better?
- `DESTDIR="test" meson install`
- lots of lv2lint checks fail, including _Plugin Instantiation_. I believe there is no point now in adding the check there with exceptions as it will not help if in the future the plugins _actually_ break...

Package Kapitonov Plugins Pack

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/aether.lv2/.gitignore
packages/aether.lv2/PKGBUILD

[**Aether**](https://github.com/Dougal-s/Aether)
- pro: smaller install size if user already has roboto fonts installed
- con: .lv2 is more system-dependent (should be ok for system-installed plugins tho)
- con: namcap throws an error about this

Package aether.lv2

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/klick/PKGBUILD

Since the last release of `klick` is so old it doesn't compile anymore, we need to apply a host of post-release patches. I tried creating a patch with all the changes in the upstream repo since the last release, but that doesn't apply cleanly to the files from the source distribution. This needs more work.

feat: add package 'klick' using releases from fork Allfifthstuning/klick

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/swh-plugins.lv2/.gitignore
packages/swh-plugins.lv2/PKGBUILD

LV2 ports of [Steve Harris' plugins suite](http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html)
- segfaults in lv2lint caused by https://github.com/swh/lv2/issues/8
- that can happen later and probably needs lots of attention
- it's already merged now and swh is planning a release soon 🎉
- still getting a missing symbol error for `buffer_write` for some reason
- not doing that for now

Package swh-plugins.lv2

---

packages/jamulus/PKGBUILD

This prevents a conflict when installing all packages from pro-audio. Thanks @jujudusud for reporting this.

Remove pro-audio group from jamulus-headless

---

packages/ola/PKGBUILD

```
Reading repository package databases...
Reading local package database...
:: installing protobuf (3.20.1-1) breaks dependency 'libprotobuf.so=30-64' required by ola
```

feat: bump pkgrel due to protobuf soname bump

---

packages/ola/PKGBUILD

This should fix #73 and some of the failing tests.
However those assertions are there for a reason so the program might start to misbehave without them, even if it's not crashing anymore...

ola: fix stdc++ assertions crashing olad

---

nvchecker/archlinux-proaudio.toml
nvchecker/run-nvchecker.cron

The notification script on the server couldn't pul the latest git commits, because the `nvchecker` config was changed locally.

fix: nvchecker config and cron script

---

packages/abcm2ps/PKGBUILD
packages/jack-matchmaker/PKGBUILD
packages/jalv-select/PKGBUILD
packages/mamba/PKGBUILD
packages/mclk.lv2/PKGBUILD
packages/midiomatic/PKGBUILD
packages/python-pyjacklib/PKGBUILD
packages/python-rtmidi/PKGBUILD
packages/qjackcapture/PKGBUILD
packages/stone-phaser/PKGBUILD
packages/string-machine/PKGBUILD
packages/ykchorus/PKGBUILD

- reverted Mamba license to `BSD`, see [this comment](https://gitlab.archlinux.org/pacman/namcap/-/merge_requests/5#note_59140) for context

bump some pkgrels to trigger AUR updates and debug builds

---

tools/prepare-build.sh

The `.tmp/packagelist` was not being created if the `PACKAGE` variable is set, leading to the _Update db_ step clearing the whole db 🤦

fix building single package

---

packages/vcvrack/PKGBUILD
packages/vcvrack/aarch64.patch

fixes compiling some plugins on aarch64

vcvrack: add objcopy rule for aarch64

---

packages/ola/PKGBUILD

Some commits were added to the referenced PR, breaking checksum and `prepare()`. However the PR is finally merged, so on the next stable release we can remove both patches and the whole `prepare()` function.

ola: fix patch source

---

packages/vcvrack/PKGBUILD
packages/vcvrack/plugins.patch

- update vcvrack-fundamental to v2.3.0
- remove broken `provides` because `libRack.so` does not actually have a `SONAME`
- add version to `vcvrack-fundamental` provide
- remove linking all libraries to plugins by default; plugins will have to link used libraries themselves

update vcvrack-fundamental to v2.3.0

---

aur/packages
packages/jamulus/PKGBUILD

Has osamc AUR user is enabled has maintainer in jamulus AUR repository, We want to use AUR like a mirror of osam repository.

add jamulus to AUR list and bump pkgrel

---

aur/packages
nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/uhhyou-plugins/PKGBUILD

Giving this another try with the newer vst3sdk package ...
TODO

Package uhhyou-plugins

---

packages/octasine/PKGBUILD

See: https://github.com/greatest-ape/OctaSine/issues/144

fix: don't include CLAP plugin on aarch64 for now

---

packages/lpd8editor/PKGBUILD

Also add missing dep on 'graphite'

fix: 'qt-base' does not provide soname dependencies

---

aur/packages
nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json
packages/simplescreenrecorder/PKGBUILD

As requested by @diovudau on the [Wishlist](https://github.com/osam-cologne/archlinux-proaudio/issues/3#issuecomment-1554416021), I packaged [SimpleScreenRecorder](https://www.maartenbaert.be/simplescreenrecorder) to be maintained here.

Package simplescreenrecorder

---

packages/simplescreenrecorder/PKGBUILD

Compilation fails with `#error neither __elf32 nor __elf64 is defined`

fix: disable aarch64 format for package simplescreenrecorder

---

HOWITWORKS.md

This came out of a chat conversation with @redtide.
I reworked and enhanced it a bit afterwards and thought it would be a handy resource to point interested parties to, to quickly explain what we are doing here.

docs: add document with high-level overview of CI build process

---

.drone.yml

Use [custom drone.io plugin](https://github.com/SpotlightKid/drone-matrixchat-notify) to send CI notifications to sonoj.org matrix server

feat:  send CI notifications to sonoj.org matrix server

---

aur/packages
nvchecker/old_ver.json
packages/dxconvert/PKGBUILD

@SpotlightKid not sure if it was left out intentionally, but since the AUR is outdated and already has osamc added as a maintainer, it makes sense to enable the sync as well

dxconvert: update to v3.2.1 and add to AUR list

---

packages/clap-example-host/PKGBUILD

... due to rtmidi soname change

fix: bump pkgrel to trigegr rebuild of clap-example-host

---

aur/packages
packages/abseil-cpp11/PKGBUILD

- legacy compatibility package of abseil-cpp
- This is required for #288 
- using this and #330, ola finally builds again 🎉

Package abseil-cpp11

---

packages/ola/PKGBUILD

- building with LTO fails
- See [AUR comment](https://aur.archlinux.org/pkgbase/ola#comment-949266)

ola: !lto build option

---

packages/paulxstretch/PKGBUILD
packages/simplescreenrecorder/.gitignore

- fixes #364 
- for reference, the change was caused by github generating slightly longer commit hashes:
```diff
--- paulxstretch/fix-juce-x11-2.patch	2024-02-04 14:48:03.554849412 +0100
+++ paulxstretch/fix-juce-x11.patch	2024-02-18 22:29:40.740732297 +0100
@@ -10,7 +10,7 @@
3 files changed, 42 insertions(+), 11 deletions(-)
diff --git a/BREAKING-CHANGES.txt b/BREAKING-CHANGES.txt
-index 9cdbc6c910c..f9517ae9c8e 100644
+index 9cdbc6c910c7..f9517ae9c8e7 100644
--- a/BREAKING-CHANGES.txt
+++ b/BREAKING-CHANGES.txt
@@ -1,6 +1,28 @@
@@ -43,7 +43,7 @@
=============
diff --git a/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp b/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp
-index 384005f9f53..3911d1d59be 100644
+index 384005f9f53b..3911d1d59be1 100644
--- …
```

paulxstretch: fix patch sha256sum

---

packages/clap-example-host/PKGBUILD
packages/vcvrack/PKGBUILD

- Closes #370 
- This will likely break the update for Manjaro as they're still on rtmidi 5

Fix clap-example-host and vcvrack for rtmidi 6

---

packages/vcvrack/PKGBUILD

- glfw 3.4 finally got released with transparent and stable support for wayland + x11, i.e. it's chosen at runtime instead of at compile time
- the [new glfw package](https://archlinux.org/packages/extra/x86_64/glfw/) has `provides=(glfw-x11 glfw-wayland)` so nothing breaks for now but that's likely to change in the future

vcvrack: use new glfw package

---

nvchecker/old_ver.json
packages/rakarrack-plus/PKGBUILD

* Set license to SPDX identifier.
* Added 'glibc' and 'libx11' to depends.
* Made cmake build dir name release-specific.

feat: update package 'alsa-utils' to 1.2.5-1

---

nvchecker/archlinux-proaudio.toml
nvchecker/old_ver.json

Versions >= 5 are not FLOSS anymore

fix: remove nvchecker config for python-pysimplegui

---

nvchecker/old_ver.json
packages/convertwithmoss/PKGBUILD
packages/convertwithmoss/convertwithmoss.sh

- some improvements towards [java package guidelines](https://wiki.archlinux.org/title/Java_package_guidelines)

convertwithmoss: update to v8.5.1

---

.drone.yml
tools/pacman.conf

Since update to fakeroot 1.35-1 it hangs when running `makepkg` in docker during CI builds.

hack: install previous fakeroot version and ignore future updates

---

packages/faustlive/PKGBUILD

- for some reason there was no sound on the current build

faustlive: bump pkgrel to rebuild for latest faust version

---

nvchecker/old_ver.json
packages/fluida.lv2/PKGBUILD

Also fix lv2lint command in check() function to ignore exported symbols

feat: update package fluida.lv2 to 0.9.3-1

---

packages/dxconvert/PKGBUILD

feat: use SPDX license identifier
fix: add 'python-qrcode' to optdepends

fix: update source hash (upstream file changed)

---

.drone.yml
packages/audiowmark/PKGBUILD

- see https://github.com/swesterfeld/audiowmark/issues/72#issuecomment-2564714535
- ffmpeg (used in tests) seems to interpret stdin
- maybe a proper fix would patch the tests to use `ffmpeg -nostdin`

audiowmark: prevent ffmpeg in check() from reading stdin

---

packages/vcvrack/PKGBUILD

- This should fix loading the Surge XT build from library, see https://github.com/osam-cologne/archlinux-proaudio/issues/97#issuecomment-1575606999

vcvrack: vendor libsamplerate

---

packages/ratatouille.lv2/PKGBUILD

See: https://github.com/brummer10/Ratatouille.lv2/issues/42

[ratatouille.lv2] fix: ensure that everything is built with GCC

---

packages/vcvrack-sicko-cv/PKGBUILD

The tag was previously removed and later added again as a new version 🤦

vcvrack-sicko-cv: fix v2.7.1 tag

---

packages/rtcqs/PKGBUILD

feat: update rtcqs to 0.6.6-1

---

.drone.yml
packages/jamulus/PKGBUILD
tools/build-env.sh
tools/prepare-build.sh

This integrates a persisted host cache configured on the CI runners by setting these config variables:
```
DRONE_RUNNER_VOLUMES=/var/cache/drone:/drone/cache
DRONE_RUNNER_ENVIRON=DRONE_CACHE:/drone/cache
```
tbf I don't know yet how well this is going to work out since my CI runners currently don't have huge storage, but let's see...

Setup basic shared cache

---

packages/vcvrack-dbrack-sequencer/.nvchecker.toml

This fixes reporting versions like `v2.6.2-dev`

vcvrack-dbrack-sequencer: fix nvchecker

---

aur/packages
packages/pluginval/.nvchecker.toml
packages/pluginval/PKGBUILD

feat: add new package 'pluginval'
